### ISSUE TITLE
Cannot call method 'get_as_text' on a null value.

### ISSUE THREAD

**Issue by valkyrienyanko** [Lasuch69/SharpGame#2]
![Untitled](https://github.com/Lasuch69/SharpGame/assets/6277739/9e1b4c49-5a9f-4b43-bf6a-fa0c0b81d9f2)
![Untitled](https://github.com/Lasuch69/SharpGame/assets/6277739/84b6889f-86e4-4cb4-bb83-d5101dc8bcc1)
![Untitled](https://github.com/Lasuch69/SharpGame/assets/6277739/de4d227a-f9f6-410d-ad82-5fac65fb751e)

## Issue
I get this error when I try to run the game.

`file` is `null` because `PATH` is pointing to a json file that does not exist on my computer. I'm not sure where "user://" directory is. Do I need to create a empty `settings.json` file here? If this is the case this could be done through script but I only have experience with C# not GDScript.

Maybe do something like
```cs
if settings.json file does not exist {
  create settings.json file
}

read settings.json file

...
```

Please note that I'm running a Windows 11 machine so the path may be different if you're running on Mac or Linux.

**Comment by Lasuch69** [comment]
I should've handled the error... The issue is that the file doesn't exist and write operation isn't used yet from what I recall.

Take a look on startup.tscn there is a line which calls the read function on Settings singleton, then comment out that line.

I will fix it ASAP, sadly my drive died yesterday.  :(

Edit:

This is the line that I am talking about: https://github.com/Lasuch69/SharpGame/blob/main/startup.tscn#L9

I recommend changing it with the editor as it is a built-in script (shouldn't be really changed outside of Godot just in case).

As the game isn't writing anything yet this function is useless for now anyway.

**Comment by Lasuch69** [comment]
For now I deleted Settings singleton as that was dead code anyway, so this is now *fixed*.
